### ISSUE TITLE
Opening two files leads to a "instance is disposed" error

### ISSUE THREAD

**Issue by punarinta** [lumeland/imagemagick-deno#11]
The following code
```ts
  await initialize();

  const imageData: Uint8Array = await Deno.readFile('image.png');
  const wmData: Uint8Array = await Deno.readFile('watermark.png')
  const wm: IMagickImage = await new Promise((resolve) => ImageMagick.read(wmData, resolve))

  await ImageMagick.read(imageData, async (img: IMagickImage) => {
    img.composite(wm)
  })
```

results in the following error
```
CLI process died because of an error Error: instance is disposed
    at MagickImage.get _instance (https://deno.land/x/imagemagick_deno@0.0.26/src/native-instance.ts:29:11)
    at https://deno.land/x/imagemagick_deno@0.0.26/src/magick-image.ts:1244:15
    at https://deno.land/x/imagemagick_deno@0.0.26/src/internal/exception/exception.ts:36:22
    at Function.use (https://deno.land/x/imagemagick_deno@0.0.26/src/internal/pointer/pointer.ts:27:14)
    at Function.usePointer (https://deno.land/x/imagemagick_deno@0.0.26/src/internal/exception/exception.ts:35:20)
    at MagickImage.composite (https://deno.land/x/imagemagick_deno@0.0.26/src/magick-image.ts:1241:15)
```

**Comment by oscarotero** [comment]
This repo contains only the code from https://github.com/dlemstra/magick-wasm converted for Deno compatibility.
Can you reproduce this error with the original Node version?

**Comment by punarinta** [comment]
@oscarotero the code with the original library works well:

```ts
const { ImageMagick, initializeImageMagick, MagickFormat } = require('@imagemagick/magick-wasm')
const fs = require('fs')

const imageData = fs.readFileSync('image.png')
const wmData = fs.readFileSync('watermark.png')

const _ = (async () => {
  await initializeImageMagick()

  ImageMagick.read(wmData, wm => {
    ImageMagick.read(imageData, image => {
      image.composite(wm)

      image.write(
        MagickFormat.Jpeg,
        data => fs.writeFileSync('result.png', data),
      )
    })
  })
})()
```

**Comment by punarinta** [comment]
Apparantly this was the problem: https://github.com/dlemstra/magick-wasm/issues/93#issuecomment-1563459037
Problem solved. Sorry for a false alarm.
